(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(column-number-mode t)
 '(company-global-modes (quote (not org-mode text-mode markdown-mode)))
 '(company-require-match nil)
 '(css-indent-offset 2)
 '(custom-enabled-themes (quote (tsdh-light)))
 '(custom-safe-themes
   (quote
    ("26d49386a2036df7ccbe802a06a759031e4455f07bda559dcf221f53e8850e69" default)))
 '(delete-selection-mode t)
 '(desktop-save-mode t)
 '(electric-pair-inhibit-predicate
   (lambda
     (c)
     (if
         (char-equal c 60)
         t
       (electric-pair-default-inhibit c))))
 '(electric-pair-mode t)
 '(fringe-mode 0 nil (fringe))
 '(global-auto-revert-mode t)
 '(global-company-mode t)
 '(global-undo-tree-mode t)
 '(global-visual-line-mode nil)
 '(lsp-ui-doc-alignment (quote window))
 '(lsp-ui-doc-border "#a0a1a7")
 '(lsp-ui-doc-delay 0.5)
 '(lsp-ui-doc-enable nil)
 '(lsp-ui-doc-max-width 80)
 '(lsp-ui-doc-position (quote bottom))
 '(lsp-ui-doc-use-childframe t)
 '(lsp-ui-doc-use-webkit nil)
 '(lsp-ui-flycheck-enable t)
 '(lsp-ui-peek-always-show t)
 '(lsp-ui-peek-enable t)
 '(lsp-ui-sideline-enable nil)
 '(next-screen-context-lines 5)
 '(package-selected-packages
   (quote
    (flycheck company-elisp haskell evil-magit evil-collection org evil-org lua-mode which-key lsp-ui company-lsp company yasnippet lsp-mode xclip yaml-mode multi-term magit evil-leader evil-surround evil-visual-mark-mode emmet-mode web-mode haskell-mode)))
 '(powerline-default-separator nil)
 '(prettier-js-command "prettier --ignore-path ~/.prettierignore")
 '(ring-bell-function (quote ignore))
 '(scroll-bar-mode nil)
 '(sentence-end-double-space nil)
 '(shift-select-mode nil)
 '(show-paren-mode t)
 '(tool-bar-mode nil)
 '(visual-line-fringe-indicators (quote (nil nil)))
 '(web-mode-code-indent-offset 2)
 '(web-mode-css-indent-offset 2)
 '(web-mode-enable-auto-pairing nil)
 '(web-mode-markup-indent-offset 2)
 '(web-mode-script-padding 0)
 '(web-mode-style-padding 0)
 '(web-mode-tests-directory "~/tests/")
 '(window-divider-default-bottom-width 13)
 '(window-divider-default-places t)
 '(window-divider-default-right-width 17)
 '(window-divider-mode t)
 '(winner-mode t)
 '(xterm-mouse-mode t))
(package-initialize)
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:family "SF Mono" :foundry "nil" :slant normal :weight normal :height 130 :width normal))))
 '(company-echo ((t nil)) t)
 '(company-tooltip ((t (:background "cornsilk" :foreground "black" :inherit fixed-pitch))))
 '(fixed-pitch ((t (:family "SF Mono"))))
 '(fixed-pitch-serif ((t (:family "SF Mono"))))
 '(fringe ((t (:background "grey98"))))
 '(lsp-ui-doc-background ((t (:background "gray95"))))
 '(lsp-ui-sideline-code-action ((t (:foreground "#a0a1a7" :slant italic))))
 '(markdown-header-face-1 ((t (:inherit outline-1))))
 '(markdown-header-face-2 ((t (:inherit outline-2))))
 '(markdown-header-face-3 ((t (:inherit outline-3))))
 '(markdown-header-face-4 ((t (:inherit outline-4))))
 '(markdown-header-face-5 ((t (:inherit outline-5))))
 '(markdown-header-face-6 ((t (:inherit outline-6))))
 '(mode-line ((t (:background "gray90" :box nil :overline "gray98"))))
 '(mode-line-buffer-id-inactive ((t (:inherit mode-line-buffer-id :background "gray98"))))
 '(mode-line-highlight ((t (:background "grey98" :foreground "black" :box nil))))
 '(mode-line-inactive ((t (:inherit mode-line :background "gray98" :foreground "#a0a1a7"))))
 '(org-block ((t (:inherit fixed-pitch))))
 '(org-block-begin-line ((t (:foreground "#a0a1a7" :slant italic :inherit fixed-pitch))))
 '(org-block-end-line ((t (:inherit org-block-begin-line))))
 '(org-code ((t (:inherit (shadow fixed-pitch)))))
 '(org-formula ((t (:foreground "Firebrick" :inherit fixed-pitch))))
 '(org-hide ((t (:inherit fixed-pitch :foreground "#fafafa"))))
 '(org-indent ((t (:inherit nil))))
 '(org-meta-line ((t (:inherit font-lock-comment-face :inherit fixed-pitch))))
 '(org-table ((t (:foreground "Blue1" :inherit fixed-pitch))))
 '(org-verbatim ((t (:inherit (shadow fixed-pitch)))))
 '(outline-1 ((t (:inherit variable-pitch :weight bold :height 1.3))))
 '(outline-2 ((t (:inherit outline-1 :weight normal :height 0.95))))
 '(outline-3 ((t (:inherit outline-1 :weight bold :height 0.9))))
 '(outline-4 ((t (:inherit outline-1 :weight normal :height 0.9))))
 '(outline-5 ((t (:inherit outline-1 :weight bold :height 120))))
 '(outline-6 ((t (:inherit outline-1 :weight bold :height 0.8))))
 '(outline-7 ((t (:inherit outline-1 :weight normal :height 0.8))))
 '(outline-8 ((t (:inherit outline-1 :weight bold :height 0.7))))
 '(powerline-active1 ((t (:inherit mode-line))))
 '(powerline-active2 ((t (:inherit mode-line))))
 '(powerline-inactive1 ((t (:inherit mode-line-inactive))))
 '(powerline-inactive2 ((t (:inherit mode-line-inactive))))
 '(variable-pitch ((t (:inherit default :foreground "gray30" :family "Libre Baskerville"))))
 '(web-mode-comment-face ((t (:inherit font-lock-comment-face))))
 '(window-divider ((t (:foreground "gray98"))))
 '(window-divider-first-pixel ((t (:foreground "gray80"))))
 '(window-divider-last-pixel ((t (:foreground "gray98")))))
